version: '3'
services:

  core:
    build:
      context: .
      dockerfile: core/Dockerfile
    hostname: core
    working_dir: /root/
    environment:
      - WELCOMER_SERVER=welcomer
      - WELCOMER_PORT=8080
      - WELLCOMER_USE_SSL=false
      - CALCULATOR_SERVER=calculator
      - CALCULATOR_PORT=8082
      - CALCULATOR_USE_SSL=false
      - AMQP_SERVER_URL=amqp://guest:guest@message-broker:5672/
    networks:
      - default
    ports:
      - '3000:3000'

  welcomer:
    build:
      context: .
      dockerfile: welcomer/Dockerfile
    hostname: welcomer
    working_dir: /root/
    environment:
      - CONNECTION_TYPE=tcp
      - CONNECTION_PORT=:8080
      - USE_SSL=false
    networks:
      - default
    ports:
      - '8080:8080'

  calculator:
    build:
      context: .
      dockerfile: calculator/Dockerfile
    hostname: calculator
    working_dir: /root/
    environment:
      - CONNECTION_TYPE=tcp
      - CONNECTION_PORT=:8082
      - USE_SSL=false
    networks:
      - default
    ports:
      - '8082:8082'
  
  notifier:
    build:
      context: .
      dockerfile: notifier/Dockerfile
    hostname: notifier
    working_dir: /root/
    environment:
      - AMQP_SERVER_URL=amqp://guest:guest@message-broker:5672/
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: message-broker
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    volumes:
      - ./notifier/services/brokerService/rabbitmq/data/:/var/lib/rabbitmq
      - ./notifier/services/brokerService/rabbitmq/log/:/var/log/rabbitmq
    restart: unless-stopped
    networks:
      - default

  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./core/store/mongo/data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  mongoExpress: # gui service for mongodb
    image : mongo-express
    depends_on:
      - mongodb
    container_name: mongo-gui
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8081:8081
    restart: unless-stopped


networks:
  default:
    external:
      name: multiverse
